# -*- coding: utf-8 -*-
"""WaterLeakDetect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eyExIA1eCcSl26VarBTi7q4gWvW5iK2-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/water_network_leak_dataset.csv")

df.head(10)

df = df.rename(columns={'Pressure_PSI': 'Pressure(Psi)','Flow_GPM':'Flow (GPM)','Velocity_FPS':'Velocity(FPS)','Temperature_F':'Temparetaure(F)',
                        'Pipe_Age_Years':'PipeAge(Years)'})
display(df.head())

df.info()

df.isnull().sum()

df.describe()

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
for i in df[['Pipe_ID','Pipe_Material','Soil_Corrosivity']]:
  label_encoder=LabelEncoder()
  df[i]=label_encoder.fit_transform(df[i])

df.head()

x=df.iloc[:,0:8]
y = df["Leak_Class"]

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=10) # Changed random_state

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

from sklearn.linear_model import LogisticRegression, LinearRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)

ypred = model.predict(xtest)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(ytest, ypred)
conf_matrix = confusion_matrix(ytest, ypred)
class_report = classification_report(ytest, ypred)

# Print results
print("Model Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Reds', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix Heatmap')
plt.show()

linearModel=LinearRegression()
linearModel.fit(xtrain, ytrain)

ypredict2=linearModel.predict(xtest)
conf_matrix2=confusion_matrix(ytest, ypred)
sns.heatmap(conf_matrix2, annot=True, cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1']
            )
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix Heatmap')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.regplot(x=ytest, y=ypredict2, scatter_kws={'alpha':0.6}, line_kws={'color':'red'})
plt.xlabel('Actual Leak Class (ytest)')
plt.ylabel('Predicted Leak Class (ypredict2)')
plt.title('Actual vs. Predicted Leak Class with Linear Regression')
plt.grid(True)
plt.show()